[tool.poetry]
name = "navtools"
version = "0.0.1"
description = "A small package of tools for PNT development."
authors = ["Tanner Koza <kozatanner@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.24.3"
pandas = "^2.0.1"
matplotlib = "^3.7.1"
seaborn = "^0.12.2"
plotly = "^5.14.1"

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
mpld3 = "^0.5.9"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
